$(document).ready(function(){
  $('.work-slider-content').slick({
    arrows:false,
    dots:true
  });
});
$(document).ready(function(){
  $('.grup-slider').slick({
    arrows:false,
    dots:true
  });
});
